/**
 * El reporte, en Markdown — el archivo que el cliente se lleva.
 *
 * Vivía dentro de `reports/page.tsx`, donde no había forma de probarlo sin
 * montar la página entera. Es una función pura de `Report` a texto, así que sale
 * al lado del motor y se prueba directo. La mudanza no cambia una línea de lo
 * que produce salvo la tabla de fuentes, que antes tenía cuatro filas escritas a
 * mano y se había quedado sin PageSpeed — la única fuente que hoy trae datos
 * reales. El export omitía justo el estado que importaba.
 */

import { DATA_SOURCE_KEYS, DATA_SOURCE_LABELS } from "./dataSources";
import type { ProfileCitation, Report } from "./types";

/**
 * La línea que dice contra qué versión de la ficha se escribió el reporte.
 *
 * Cuatro frases para cuatro estados, y la de `error` NO se parece a la de
 * `none`: el cliente que lee «no strategic profile has been published» y el que
 * lee «the strategic profile could not be read» tienen que hacer cosas
 * distintas. El id va entero y no recortado: es lo que alguien pega en un
 * `select ... where id = ...` para resolver la cita, que es la mitad (b) de la
 * puerta H1.2.
 */
function citationLine(c: ProfileCitation): string {
  switch (c.status) {
    case "cited":
      return `Written against strategic profile **version ${c.version}**, published ${new Date(c.publishedAt).toLocaleDateString()} — version id \`${c.versionId}\`.`;
    case "none":
      return "No strategic profile has been published for this business yet, so this report cites none.";
    case "demo":
      return "Demo report: there is no organisation behind it, so there is no strategic profile to cite.";
    case "error":
      return `The strategic profile could not be read (${c.reason}), so this report cites none. This is a failure on our side, not a missing profile.`;
  }
}

export function reportToMarkdown(r: Report): string {
  const issues = r.issues
    .map(
      (i, idx) =>
        `\n### ${String(idx + 1).padStart(2, "0")} — [${i.severity}] ${i.title}\n\n` +
        `**Category:** ${i.category} · **Impact:** ${i.impact} · **Difficulty:** ${i.difficulty}\n\n` +
        `**Why it matters:** ${i.rationale}\n\n` +
        `**Evidence:**\n${i.evidence.map((e) => `- ${e}`).join("\n")}\n\n` +
        `**Recommendation:** ${i.recommendation}`,
    )
    .join("\n");

  const actions = r.actions
    .map(
      (a) =>
        `| W${String(a.week).padStart(2, "0")} | ${a.title} | ${a.owner} | ${a.impact} |`,
    )
    .join("\n");

  const kpis = r.kpis
    .map((k) => `| ${k.label} | ${k.currentValue} | ${k.target} | ${k.cadence} |`)
    .join("\n");

  // Recorrido, y no cuatro filas escritas a mano: la lista escrita a mano se
  // había quedado sin PageSpeed —la única fuente que hoy trae datos reales—, así
  // que el export omitía justo el estado que importaba. Recorrer
  // DATA_SOURCE_KEYS hace que una fuente nueva aparezca acá sola.
  const sources = DATA_SOURCE_KEYS.map(
    (key) => `| ${DATA_SOURCE_LABELS[key]} | ${r.dataSourceHealth[key]} |`,
  ).join("\n");

  return `# ${r.businessName} — Growth Report
Generated: ${new Date(r.generatedAt).toLocaleString()}
Engine: ${r.generator}

## Executive Summary

${r.summary}

## Current State

- **Local rank:** ${r.state.localRank !== null ? `#${r.state.localRank}` : "—"}${r.state.localRankDelta !== null ? ` (Δ ${r.state.localRankDelta > 0 ? "+" : ""}${r.state.localRankDelta})` : ""}
- **GBP score:** ${r.state.gbpScore}%
- **Reviews:** ${r.state.reviewsTotal} total · ${r.state.reviewsServiceMentions} mention featured service
- **Content drafts:** ${r.state.contentApproved} approved / ${r.state.contentTotal} total
- **Competitors tracked:** ${r.state.competitorsTracked}
- **90-day plan completion:** ${r.state.planCompletion}%

## Priority Issues
${issues}

## 90-Day Action Plan

| Week | Action | Owner | Impact |
|------|--------|-------|--------|
${actions}

## KPIs to Track

| KPI | Current | Target | Cadence |
|-----|---------|--------|---------|
${kpis}

## Strategic Profile

${citationLine(r.profileCitation)}

## Data Source Health

| Source | Status |
|--------|--------|
${sources}

> ${r.dataSourceHealth.note}

---
*Generated by Vulkan Growth OS · Reporting Engine ${r.generator}*
`;
}
