import { Card, Badge, PageHeader, Progress } from "@/components/ui";
import { RankingChart, ReviewsChart } from "@/components/charts";
import { metrics, priorityTasks, rankingTrend, reviewsGrowth } from "@/lib/mock/data";
import { AlertTriangle, CheckCircle2, Sparkles } from "lucide-react";

export default function DashboardPage() {
  return <><PageHeader title="Local SEO Command Center" description="A premium demo dashboard to guide Mörby Fotvård och Skönhet toward stronger visibility for ansiktsbehandling in Danderyd." action={<Badge variant="gold">Live integrations ready for Phase 2</Badge>} />
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{metrics.map((m) => <Card key={m.label} className="gradient-card"><p className="text-sm text-muted-foreground">{m.label}</p><div className="mt-3 flex items-end justify-between"><p className="text-4xl font-bold text-ink">{m.value}</p><Badge>{m.delta}</Badge></div><p className="mt-3 text-sm text-muted-foreground">{m.note}</p></Card>)}</div>
  <div className="mt-6 grid gap-6 xl:grid-cols-3"><Card className="xl:col-span-2"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold text-ink">Ranking trend</h2><Badge>Lower is better</Badge></div><RankingChart data={rankingTrend} /></Card><Card><h2 className="text-xl font-bold text-ink">AI Priority Insight</h2><div className="mt-5 rounded-2xl bg-cream p-4"><Sparkles className="mb-3 h-5 w-5 text-gold" /><p className="font-semibold text-ink">The fastest win is semantic reinforcement.</p><p className="mt-2 text-sm text-muted-foreground">Align the service page, Google Business Profile services, posts and reviews around ansiktsbehandling, hudvård and Danderyd.</p></div><div className="mt-5"><div className="mb-2 flex justify-between text-sm"><span>90-day plan</span><span>18%</span></div><Progress value={18} /></div></Card></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-2"><Card><h2 className="text-xl font-bold text-ink">Reviews growth</h2><ReviewsChart data={reviewsGrowth} /></Card><Card><div className="mb-4 flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-gold" /><h2 className="text-xl font-bold text-ink">Today’s priority tasks</h2></div><div className="space-y-3">{priorityTasks.map((t) => <div key={t.title} className="rounded-2xl border bg-white p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-ink">{t.title}</p><p className="mt-1 text-sm text-muted-foreground">{t.category} · Impact: {t.impact}</p></div><Badge variant={t.priority === "Critical" ? "critical" : "default"}>{t.priority}</Badge></div></div>)}</div></Card></div>
  <Card className="mt-6"><div className="flex items-start gap-3"><CheckCircle2 className="mt-1 h-5 w-5 text-sage" /><div><h2 className="text-xl font-bold text-ink">Phase 1 status</h2><p className="mt-2 text-muted-foreground">The app is currently using mock data. The architecture is prepared for OpenAI, Google Places, Google Business Profile, Search Console and GA4 integrations.</p></div></div></Card></>;
}
